### ISSUE TITLE
在构建项目时遇到ImportError

### ISSUE THREAD

**Issue by Atrewin** [eastonYi/wav2vec#2]
你好，我正在尝试在本地运行你们的wav2vec项目，但我遇到了一些问题。

我在尝试运行训练脚本时遇到了一个ImportError，错误信息提示我需要构建Cython组件。以下是我遇到的错误信息：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yejinhui/Projects/wav2vec/src/train.py", line 324, in <module>
    cli_main()
  File "/home/yejinhui/Projects/wav2vec/src/train.py", line 320, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/yejinhui/Projects/wav2vec/src/tools/distributed_utils.py", line 181, in call_main
    main(args, **kwargs)
  File "/home/yejinhui/Projects/wav2vec/src/train.py", line 106, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/yejinhui/Projects/wav2vec/src/tools/checkpoint_utils.py", line 185, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "/home/yejinhui/Projects/wav2vec/src/trainer.py", line 305, in get_train_iterator
    return self.task.get_batch_iterator(
  File "/home/yejinhui/Projects/wav2vec/src/tasks/fairseq_task.py", line 213, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "/home/yejinhui/Projects/wav2vec/src/dataload/fairseq_dataset.py", line 118, in batch_by_size
    return data_utils.batch_by_size(
  File "/home/yejinhui/Projects/wav2vec/src/dataload/data_utils.py", line 243, in batch_by_size
    raise ImportError(
ImportError: Please build Cython components with: `pip install --editable .`
根据错误信息，我尝试使用pip install --editable .命令在项目根目录下构建Cython组件，但这个命令提示我项目目录下没有setup.py或pyproject.toml文件。

我对此感到困惑，希望你们能提供一些帮助。我是否需要为这个项目的某些特定部分单独执行构建命令？或者是否有其他我可能错过的步骤？

**Comment by zhenlongsong** [comment]
在fairseq文件下有setup文件

**Comment by kang-qingjiu** [comment]
> 在fairseq文件下有setup文件

fairseq文件在哪。。。

**Comment by kang-qingjiu** [comment]
> 在fairseq文件下有setup文件

我下载了fairseq的源代码，并且成功运行setup文件，但是题主问题还是存在

**Comment by rosotron** [comment]
You guys ever solved it?
